/* 
 * Fearsome Foursome
 * Object Oriented Programming
 * Final Project
 * 
 * This project is a prototype for a customer information system.
 * It allows a customer to create a login, log in, reset their password,
 * and modify their account information.
 * A tab of test buttons is provided because this is a prototype; data is
 * not persistent.
 * 
 */
package olympicstore;


public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      tabCstLogin = new javax.swing.JTabbedPane();
      CustomerLogin = new javax.swing.JPanel();
      CstEMailAddressLabel = new javax.swing.JLabel();
      CstPasswordLabel = new javax.swing.JLabel();
      LoginTabEmailField = new javax.swing.JTextField();
      LoginTabOKButton = new javax.swing.JButton();
      LoginTabCancelButton = new javax.swing.JButton();
      LoginTabPasswordField = new javax.swing.JPasswordField();
      OlympicPride = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      NewCustomer = new javax.swing.JPanel();
      ReqFieldInstruct = new javax.swing.JLabel();
      EmailAddress = new javax.swing.JLabel();
      NewTabEmailField = new javax.swing.JTextField();
      OlympicPride1 = new javax.swing.JLabel();
      NewPasswordLabel = new javax.swing.JLabel();
      ConfirmNewPasswordLabel = new javax.swing.JLabel();
      NewTabCreatePasswordField = new javax.swing.JPasswordField();
      NewTabConfirmPasswordField = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      NewTabQuestionDropdown = new javax.swing.JComboBox();
      NewTabAnswerField = new javax.swing.JTextField();
      NewTabSaveButton = new javax.swing.JButton();
      NewTabCancelButton = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      ForgotPassword = new javax.swing.JPanel();
      ResetEMailAddressLabel = new javax.swing.JLabel();
      ResetSecurityQuestionLabel = new javax.swing.JLabel();
      ForgotTabDropdown = new javax.swing.JComboBox();
      ForgotTabAnswerField = new javax.swing.JTextField();
      ForgotTabEmailField = new javax.swing.JTextField();
      ForgotTabOKButton = new javax.swing.JButton();
      ForgotTabCancelButton = new javax.swing.JButton();
      OlympicPride2 = new javax.swing.JLabel();
      ResetAnswer = new javax.swing.JLabel();
      ReqFieldInstruct1 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      ModifyCustomerInfo = new javax.swing.JPanel();
      ModifyTabLoadButton = new javax.swing.JButton();
      jLabel9 = new javax.swing.JLabel();
      OlympicPride5 = new javax.swing.JLabel();
      EmailAddress1 = new javax.swing.JLabel();
      ModifyTabEmailField = new javax.swing.JTextField();
      ModBillCardNumberLabel = new javax.swing.JLabel();
      ModBillCardExpDateLabel = new javax.swing.JLabel();
      ModBillCardHolderNameLabel = new javax.swing.JLabel();
      ModifyTabCardNumField = new javax.swing.JTextField();
      ModifyTabCardExpField = new javax.swing.JFormattedTextField();
      ModifyTabCardNameField = new javax.swing.JTextField();
      ModShipFirstNameLabel = new javax.swing.JLabel();
      ModShipLastNameLabel = new javax.swing.JLabel();
      ModShipAddress1Label = new javax.swing.JLabel();
      ModShipAddress2Label = new javax.swing.JLabel();
      ModShipCityLabel = new javax.swing.JLabel();
      ModShipStateLabel = new javax.swing.JLabel();
      ModifyTabShipFNameField = new javax.swing.JTextField();
      ModifyTabShipLNameField = new javax.swing.JTextField();
      ModifyTabShipAddress1Field = new javax.swing.JTextField();
      ModifyTabShipAddress2Field = new javax.swing.JTextField();
      ModifyTabShipCityField = new javax.swing.JTextField();
      ModifyTabShipStateDropdown = new javax.swing.JComboBox();
      ModShipZipCode = new javax.swing.JLabel();
      ModifyTabShipZIPField = new javax.swing.JFormattedTextField();
      ModShipPhoneNumberLabel = new javax.swing.JLabel();
      ModifyTabShipPhoneField = new javax.swing.JFormattedTextField();
      ModBillFirstNameLabel = new javax.swing.JLabel();
      ModBillLastNameLabel = new javax.swing.JLabel();
      ModBillAddress1LineLabel = new javax.swing.JLabel();
      ModBillAddress2LineLabel = new javax.swing.JLabel();
      ModBillCityLabel = new javax.swing.JLabel();
      ModBillStateLabel = new javax.swing.JLabel();
      ModifyTabBillStateDropdown = new javax.swing.JComboBox();
      ModBillZipCodeLabel = new javax.swing.JLabel();
      ModifyTabBillZIPField = new javax.swing.JFormattedTextField();
      ModifyTabBillFNameField = new javax.swing.JTextField();
      ModifyTabBillLNameField = new javax.swing.JTextField();
      ModifyTabBillAddress1Field = new javax.swing.JTextField();
      ModifyTabBillAddress2Field = new javax.swing.JTextField();
      ModifyTabBillCityField = new javax.swing.JTextField();
      ModBillPhoneNumberLabel = new javax.swing.JLabel();
      ModifyTabBillPhoneField = new javax.swing.JFormattedTextField();
      ShippingInfoLabel = new javax.swing.JLabel();
      BillingInfoLabel = new javax.swing.JLabel();
      ModifyTabSaveButton = new javax.swing.JButton();
      ModifyTabCancelButton = new javax.swing.JButton();
      Test = new javax.swing.JPanel();
      TestTabLoadCustomersButton = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 892, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 406, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      CstEMailAddressLabel.setText("E-Mail Address");

      CstPasswordLabel.setText("Password");

      LoginTabOKButton.setText("OK");
      LoginTabOKButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            LoginTabOKButtonActionPerformed(evt);
         }
      });

      LoginTabCancelButton.setText("Cancel");
      LoginTabCancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            LoginTabCancelButtonActionPerformed(evt);
         }
      });

      LoginTabPasswordField.setText("jPasswordField1");

      OlympicPride.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride.setText("Olympic Pride");

      jLabel2.setText("Color label");

      javax.swing.GroupLayout CustomerLoginLayout = new javax.swing.GroupLayout(CustomerLogin);
      CustomerLogin.setLayout(CustomerLoginLayout);
      CustomerLoginLayout.setHorizontalGroup(
         CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(CustomerLoginLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(CustomerLoginLayout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addContainerGap())
               .addGroup(CustomerLoginLayout.createSequentialGroup()
                  .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(CustomerLoginLayout.createSequentialGroup()
                        .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(CstEMailAddressLabel)
                           .addComponent(CstPasswordLabel))
                        .addGap(26, 26, 26)
                        .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(LoginTabEmailField)
                           .addComponent(LoginTabPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(LoginTabOKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(LoginTabCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addComponent(OlympicPride, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 472, Short.MAX_VALUE))))
      );
      CustomerLoginLayout.setVerticalGroup(
         CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(CustomerLoginLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(OlympicPride, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(CstEMailAddressLabel)
                  .addComponent(LoginTabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(LoginTabOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(CstPasswordLabel)
               .addComponent(LoginTabPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(LoginTabCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(308, Short.MAX_VALUE))
      );

      tabCstLogin.addTab("Customer Login", CustomerLogin);

      NewCustomer.setPreferredSize(new java.awt.Dimension(1328, 432));

      ReqFieldInstruct.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
      ReqFieldInstruct.setForeground(new java.awt.Color(255, 0, 51));
      ReqFieldInstruct.setText("* indicates required field");

      EmailAddress.setText("Email Address *");

      NewTabEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            NewTabEmailFieldFocusGained(evt);
         }
      });

      OlympicPride1.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride1.setText("Olympic Pride");

      NewPasswordLabel.setText("Create New Password *");

      ConfirmNewPasswordLabel.setText("Confirm New Password *");

      NewTabCreatePasswordField.setText("jPasswordField2");

      NewTabConfirmPasswordField.setText("jPasswordField2");

      jLabel1.setText("Security Question *");

      jLabel3.setText("Security Answer *");

      NewTabQuestionDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One:", "What is your mother maiden name", "What is your dog name", "What was your school name" }));

      NewTabSaveButton.setText("Save");
      NewTabSaveButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            NewTabSaveButtonActionPerformed(evt);
         }
      });

      NewTabCancelButton.setText("Cancel");
      NewTabCancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            NewTabCancelButtonActionPerformed(evt);
         }
      });

      jLabel4.setText("Color Label");

      javax.swing.GroupLayout NewCustomerLayout = new javax.swing.GroupLayout(NewCustomer);
      NewCustomer.setLayout(NewCustomerLayout);
      NewCustomerLayout.setHorizontalGroup(
         NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(NewCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addComponent(OlympicPride1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(ReqFieldInstruct, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ConfirmNewPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addComponent(NewPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(EmailAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(NewTabEmailField)
                           .addComponent(NewTabCreatePasswordField)
                           .addComponent(NewTabQuestionDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(NewTabAnswerField)
                           .addComponent(NewTabConfirmPasswordField))))
                  .addGap(161, 161, 161)
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(NewTabSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(NewTabCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addContainerGap(68, Short.MAX_VALUE))))
      );
      NewCustomerLayout.setVerticalGroup(
         NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(NewCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(OlympicPride1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(ReqFieldInstruct))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EmailAddress)
               .addComponent(NewTabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(NewTabSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(NewPasswordLabel)
                     .addComponent(NewTabCreatePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(NewTabConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ConfirmNewPasswordLabel)))
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addGap(23, 23, 23)
                  .addComponent(NewTabCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(NewTabQuestionDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addGap(6, 6, 6)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(NewTabAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addContainerGap(280, Short.MAX_VALUE))
      );

      tabCstLogin.addTab("New Customers", NewCustomer);

      ResetEMailAddressLabel.setText("E-Mail Address *");

      ResetSecurityQuestionLabel.setText("Security Question *");

      ForgotTabDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One:", "What is your mother maiden name", "What is your dog name", "What was your school name" }));
      ForgotTabDropdown.setToolTipText("");

      ForgotTabOKButton.setText("OK");
      ForgotTabOKButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ForgotTabOKButtonActionPerformed(evt);
         }
      });

      ForgotTabCancelButton.setText("Cancel");
      ForgotTabCancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ForgotTabCancelButtonActionPerformed(evt);
         }
      });

      OlympicPride2.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride2.setText("Olympic Pride");

      ResetAnswer.setText("Answer *");

      ReqFieldInstruct1.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
      ReqFieldInstruct1.setForeground(new java.awt.Color(255, 0, 51));
      ReqFieldInstruct1.setText("* indicates required field");

      jLabel5.setText("Color Label");

      javax.swing.GroupLayout ForgotPasswordLayout = new javax.swing.GroupLayout(ForgotPassword);
      ForgotPassword.setLayout(ForgotPasswordLayout);
      ForgotPasswordLayout.setHorizontalGroup(
         ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ForgotPasswordLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ForgotPasswordLayout.createSequentialGroup()
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(OlympicPride2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ReqFieldInstruct1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ForgotPasswordLayout.createSequentialGroup()
                           .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ResetSecurityQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(ResetEMailAddressLabel)
                              .addComponent(ResetAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addGap(18, 18, 18)
                           .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ForgotTabAnswerField)
                              .addComponent(ForgotTabDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(ForgotTabEmailField))
                           .addGap(18, 18, 18)
                           .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ForgotTabOKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(ForgotTabCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))))
                  .addGap(0, 479, Short.MAX_VALUE))
               .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      ForgotPasswordLayout.setVerticalGroup(
         ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ForgotPasswordLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(OlympicPride2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ReqFieldInstruct1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
            .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ForgotPasswordLayout.createSequentialGroup()
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ForgotTabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ResetEMailAddressLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ForgotTabDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ResetSecurityQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(ForgotTabAnswerField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                     .addComponent(ResetAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addGroup(ForgotPasswordLayout.createSequentialGroup()
                  .addGap(15, 15, 15)
                  .addComponent(ForgotTabOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(ForgotTabCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(230, 230, 230))
      );

      tabCstLogin.addTab("Forgot Password", ForgotPassword);

      ModifyTabLoadButton.setText("Load");
      ModifyTabLoadButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabLoadButtonActionPerformed(evt);
         }
      });

      jLabel9.setText("Color label");

      OlympicPride5.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride5.setText("Olympic Pride");

      EmailAddress1.setText("Email Address *");

      ModifyTabEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabEmailFieldFocusGained(evt);
         }
      });

      ModBillCardNumberLabel.setText("Card Number");

      ModBillCardExpDateLabel.setText("Card Exp. Date");

      ModBillCardHolderNameLabel.setText("Card Holder Name");

      ModifyTabCardNumField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabCardNumFieldFocusGained(evt);
         }
      });

      ModifyTabCardExpField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("mm/dd/yyyy"))));

      ModifyTabCardNameField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabCardNameFieldActionPerformed(evt);
         }
      });
      ModifyTabCardNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabCardNameFieldFocusGained(evt);
         }
      });

      ModShipFirstNameLabel.setText("First Name *");

      ModShipLastNameLabel.setText("Last Name *");

      ModShipAddress1Label.setText("Address 1 *");

      ModShipAddress2Label.setForeground(new java.awt.Color(51, 51, 255));
      ModShipAddress2Label.setText("Address 2");

      ModShipCityLabel.setText("City *");

      ModShipStateLabel.setText("State *");

      ModifyTabShipFNameField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabShipFNameFieldActionPerformed(evt);
         }
      });
      ModifyTabShipFNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipFNameFieldFocusGained(evt);
         }
      });

      ModifyTabShipLNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipLNameFieldFocusGained(evt);
         }
      });

      ModifyTabShipAddress1Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipAddress1FieldFocusGained(evt);
         }
      });

      ModifyTabShipAddress2Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipAddress2FieldFocusGained(evt);
         }
      });

      ModifyTabShipCityField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipCityFieldFocusGained(evt);
         }
      });

      ModifyTabShipStateDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "Washington D.C.", "West Virginia", "Wisconsin", "Wyoming" }));
      ModifyTabShipStateDropdown.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabShipStateDropdownActionPerformed(evt);
         }
      });

      ModShipZipCode.setText("Zip Code *");

      ModifyTabShipZIPField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
      ModifyTabShipZIPField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabShipZIPFieldActionPerformed(evt);
         }
      });
      ModifyTabShipZIPField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipZIPFieldFocusGained(evt);
         }
      });

      ModShipPhoneNumberLabel.setForeground(new java.awt.Color(51, 51, 255));
      ModShipPhoneNumberLabel.setText("Phone Number");

      ModifyTabShipPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
      ModifyTabShipPhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabShipPhoneFieldFocusGained(evt);
         }
      });

      ModBillFirstNameLabel.setText("First Name *");

      ModBillLastNameLabel.setText("Last Name *");

      ModBillAddress1LineLabel.setText("Address 1 *");

      ModBillAddress2LineLabel.setForeground(new java.awt.Color(51, 51, 255));
      ModBillAddress2LineLabel.setText("Address 2");

      ModBillCityLabel.setText("City *");

      ModBillStateLabel.setText("State *");

      ModifyTabBillStateDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "Washington D.C.", "West Virginia", "Wisconsin", "Wyoming" }));
      ModifyTabBillStateDropdown.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabBillStateDropdownActionPerformed(evt);
         }
      });

      ModBillZipCodeLabel.setText("Zip Code *");

      ModifyTabBillZIPField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
      ModifyTabBillZIPField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabBillZIPFieldActionPerformed(evt);
         }
      });
      ModifyTabBillZIPField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillZIPFieldFocusGained(evt);
         }
      });

      ModifyTabBillFNameField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabBillFNameFieldActionPerformed(evt);
         }
      });
      ModifyTabBillFNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillFNameFieldFocusGained(evt);
         }
      });

      ModifyTabBillLNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillLNameFieldFocusGained(evt);
         }
      });

      ModifyTabBillAddress1Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillAddress1FieldFocusGained(evt);
         }
      });

      ModifyTabBillAddress2Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillAddress2FieldFocusGained(evt);
         }
      });

      ModifyTabBillCityField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillCityFieldFocusGained(evt);
         }
      });

      ModBillPhoneNumberLabel.setForeground(new java.awt.Color(51, 51, 255));
      ModBillPhoneNumberLabel.setText("Phone Number");

      ModifyTabBillPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
      ModifyTabBillPhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModifyTabBillPhoneFieldFocusGained(evt);
         }
      });

      ShippingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      ShippingInfoLabel.setText("Shipping Information");

      BillingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      BillingInfoLabel.setText("Billing Information");

      ModifyTabSaveButton.setText("Save");
      ModifyTabSaveButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabSaveButtonActionPerformed(evt);
         }
      });

      ModifyTabCancelButton.setText("Cancel");
      ModifyTabCancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModifyTabCancelButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout ModifyCustomerInfoLayout = new javax.swing.GroupLayout(ModifyCustomerInfo);
      ModifyCustomerInfo.setLayout(ModifyCustomerInfoLayout);
      ModifyCustomerInfoLayout.setHorizontalGroup(
         ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(ModShipFirstNameLabel)
                           .addComponent(ModShipLastNameLabel)
                           .addComponent(ModShipCityLabel)
                           .addComponent(ModShipAddress1Label)
                           .addComponent(ModShipAddress2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(ModifyTabShipAddress2Field)
                           .addComponent(ModifyTabShipAddress1Field)
                           .addComponent(ModifyTabShipFNameField)
                           .addComponent(ModifyTabShipLNameField)
                           .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                              .addComponent(ModifyTabShipStateDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(ModShipZipCode)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(ModifyTabShipZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addComponent(ModifyTabShipCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addComponent(ModShipStateLabel)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModShipPhoneNumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ModifyTabShipPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(EmailAddress1)
                        .addGap(18, 18, 18)
                        .addComponent(ModifyTabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModifyTabLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyCustomerInfoLayout.createSequentialGroup()
                  .addComponent(ShippingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModifyTabSaveButton)
                        .addGap(28, 28, 28)
                        .addComponent(ModifyTabCancelButton))
                     .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(ModBillCardHolderNameLabel)
                              .addComponent(ModBillCardExpDateLabel)
                              .addComponent(ModBillCardNumberLabel))
                           .addGap(11, 11, 11)
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ModifyTabCardNumField, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                              .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                 .addComponent(ModifyTabCardExpField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                 .addGap(190, 190, 190))
                              .addComponent(ModifyTabCardNameField)))
                        .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(ModBillFirstNameLabel)
                              .addComponent(ModBillLastNameLabel)
                              .addComponent(ModBillCityLabel)
                              .addComponent(ModBillAddress1LineLabel)
                              .addComponent(ModBillAddress2LineLabel)
                              .addComponent(ModBillStateLabel)
                              .addComponent(ModBillPhoneNumberLabel))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ModifyTabBillAddress2Field)
                              .addComponent(ModifyTabBillAddress1Field)
                              .addComponent(ModifyTabBillFNameField)
                              .addComponent(ModifyTabBillLNameField)
                              .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                 .addComponent(ModifyTabBillStateDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addComponent(ModBillZipCodeLabel)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addComponent(ModifyTabBillZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(ModifyTabBillCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                 .addGap(22, 22, 22)
                                 .addComponent(ModifyTabBillPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(BillingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(81, 81, 81))
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addComponent(OlympicPride5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))))
      );
      ModifyCustomerInfoLayout.setVerticalGroup(
         ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(OlympicPride5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(24, 24, 24)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(EmailAddress1)
                     .addComponent(ModifyTabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModifyTabLoadButton))
                  .addGap(35, 35, 35)
                  .addComponent(ShippingInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                  .addGap(18, 18, 18))
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(BillingInfoLabel)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCardNumberLabel)
                     .addComponent(ModifyTabCardNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCardExpDateLabel)
                     .addComponent(ModifyTabCardExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCardHolderNameLabel)
                     .addComponent(ModifyTabCardNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(10, 10, 10)))
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModBillFirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModBillLastNameLabel)
                        .addGap(7, 7, 7))
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModifyTabBillFNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModifyTabBillLNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                  .addGap(3, 3, 3)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillAddress1LineLabel)
                     .addComponent(ModifyTabBillAddress1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModifyTabBillAddress2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillAddress2LineLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModifyTabBillCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillCityLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModifyTabBillStateDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillZipCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModifyTabBillZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillStateLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillPhoneNumberLabel)
                     .addComponent(ModifyTabBillPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModShipFirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModShipLastNameLabel)
                        .addGap(7, 7, 7))
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModifyTabShipFNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModifyTabShipLNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                  .addGap(3, 3, 3)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModShipAddress1Label)
                     .addComponent(ModifyTabShipAddress1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModifyTabShipAddress2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModShipAddress2Label))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModifyTabShipCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModShipCityLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ModShipStateLabel)
                     .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ModifyTabShipStateDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModShipZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModifyTabShipZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModifyTabShipPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModShipPhoneNumberLabel))))
            .addGap(25, 25, 25)
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(ModifyTabSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(ModifyTabCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(66, 66, 66))
      );

      tabCstLogin.addTab("Modify Customer Info", ModifyCustomerInfo);

      TestTabLoadCustomersButton.setText("Load Demo Customers");

      jButton2.setText("Place Demo Orders");

      jButton3.setText("Test_2");

      jButton4.setText("Test_3");

      jButton5.setText("Test_1");

      javax.swing.GroupLayout TestLayout = new javax.swing.GroupLayout(Test);
      Test.setLayout(TestLayout);
      TestLayout.setHorizontalGroup(
         TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(TestLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(TestTabLoadCustomersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(765, Short.MAX_VALUE))
      );
      TestLayout.setVerticalGroup(
         TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(TestLayout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(TestTabLoadCustomersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(242, Short.MAX_VALUE))
      );

      tabCstLogin.addTab("Test", Test);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabCstLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabCstLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void NewTabEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewTabEmailFieldFocusGained
      NewTabEmailField.selectAll();
   }//GEN-LAST:event_NewTabEmailFieldFocusGained

   private void ModifyTabBillPhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillPhoneFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillPhoneFieldFocusGained

   private void ModifyTabBillCityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillCityFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillCityFieldFocusGained

   private void ModifyTabBillAddress2FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillAddress2FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillAddress2FieldFocusGained

   private void ModifyTabBillAddress1FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillAddress1FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillAddress1FieldFocusGained

   private void ModifyTabBillLNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillLNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillLNameFieldFocusGained

   private void ModifyTabBillFNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillFNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillFNameFieldFocusGained

   private void ModifyTabBillFNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabBillFNameFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillFNameFieldActionPerformed

   private void ModifyTabBillZIPFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabBillZIPFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillZIPFieldFocusGained

   private void ModifyTabBillZIPFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabBillZIPFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillZIPFieldActionPerformed

   private void ModifyTabBillStateDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabBillStateDropdownActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabBillStateDropdownActionPerformed

   private void ModifyTabShipPhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipPhoneFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipPhoneFieldFocusGained

   private void ModifyTabShipZIPFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipZIPFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipZIPFieldFocusGained

   private void ModifyTabShipZIPFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabShipZIPFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipZIPFieldActionPerformed

   private void ModifyTabShipStateDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabShipStateDropdownActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipStateDropdownActionPerformed

   private void ModifyTabShipCityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipCityFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipCityFieldFocusGained

   private void ModifyTabShipAddress2FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipAddress2FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipAddress2FieldFocusGained

   private void ModifyTabShipAddress1FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipAddress1FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipAddress1FieldFocusGained

   private void ModifyTabShipLNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipLNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipLNameFieldFocusGained

   private void ModifyTabShipFNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabShipFNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipFNameFieldFocusGained

   private void ModifyTabShipFNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabShipFNameFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabShipFNameFieldActionPerformed

   private void ModifyTabCardNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabCardNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabCardNameFieldFocusGained

   private void ModifyTabCardNumFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabCardNumFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabCardNumFieldFocusGained

   private void ModifyTabEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModifyTabEmailFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabEmailFieldFocusGained

   private void ModifyTabCardNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabCardNameFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabCardNameFieldActionPerformed

   private void LoginTabOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTabOKButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_LoginTabOKButtonActionPerformed

   private void LoginTabCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTabCancelButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_LoginTabCancelButtonActionPerformed

   private void NewTabSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTabSaveButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_NewTabSaveButtonActionPerformed

   private void NewTabCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTabCancelButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_NewTabCancelButtonActionPerformed

   private void ForgotTabOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotTabOKButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ForgotTabOKButtonActionPerformed

   private void ForgotTabCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotTabCancelButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ForgotTabCancelButtonActionPerformed

   private void ModifyTabLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabLoadButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabLoadButtonActionPerformed

   private void ModifyTabSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabSaveButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabSaveButtonActionPerformed

   private void ModifyTabCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTabCancelButtonActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModifyTabCancelButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel BillingInfoLabel;
   private javax.swing.JLabel ConfirmNewPasswordLabel;
   private javax.swing.JLabel CstEMailAddressLabel;
   private javax.swing.JLabel CstPasswordLabel;
   private javax.swing.JPanel CustomerLogin;
   private javax.swing.JLabel EmailAddress;
   private javax.swing.JLabel EmailAddress1;
   private javax.swing.JPanel ForgotPassword;
   private javax.swing.JTextField ForgotTabAnswerField;
   private javax.swing.JButton ForgotTabCancelButton;
   private javax.swing.JComboBox ForgotTabDropdown;
   private javax.swing.JTextField ForgotTabEmailField;
   private javax.swing.JButton ForgotTabOKButton;
   private javax.swing.JButton LoginTabCancelButton;
   private javax.swing.JTextField LoginTabEmailField;
   private javax.swing.JButton LoginTabOKButton;
   private javax.swing.JPasswordField LoginTabPasswordField;
   private javax.swing.JLabel ModBillAddress1LineLabel;
   private javax.swing.JLabel ModBillAddress2LineLabel;
   private javax.swing.JLabel ModBillCardExpDateLabel;
   private javax.swing.JLabel ModBillCardHolderNameLabel;
   private javax.swing.JLabel ModBillCardNumberLabel;
   private javax.swing.JLabel ModBillCityLabel;
   private javax.swing.JLabel ModBillFirstNameLabel;
   private javax.swing.JLabel ModBillLastNameLabel;
   private javax.swing.JLabel ModBillPhoneNumberLabel;
   private javax.swing.JLabel ModBillStateLabel;
   private javax.swing.JLabel ModBillZipCodeLabel;
   private javax.swing.JLabel ModShipAddress1Label;
   private javax.swing.JLabel ModShipAddress2Label;
   private javax.swing.JLabel ModShipCityLabel;
   private javax.swing.JLabel ModShipFirstNameLabel;
   private javax.swing.JLabel ModShipLastNameLabel;
   private javax.swing.JLabel ModShipPhoneNumberLabel;
   private javax.swing.JLabel ModShipStateLabel;
   private javax.swing.JLabel ModShipZipCode;
   private javax.swing.JPanel ModifyCustomerInfo;
   private javax.swing.JTextField ModifyTabBillAddress1Field;
   private javax.swing.JTextField ModifyTabBillAddress2Field;
   private javax.swing.JTextField ModifyTabBillCityField;
   private javax.swing.JTextField ModifyTabBillFNameField;
   private javax.swing.JTextField ModifyTabBillLNameField;
   private javax.swing.JFormattedTextField ModifyTabBillPhoneField;
   private javax.swing.JComboBox ModifyTabBillStateDropdown;
   private javax.swing.JFormattedTextField ModifyTabBillZIPField;
   private javax.swing.JButton ModifyTabCancelButton;
   private javax.swing.JFormattedTextField ModifyTabCardExpField;
   private javax.swing.JTextField ModifyTabCardNameField;
   private javax.swing.JTextField ModifyTabCardNumField;
   private javax.swing.JTextField ModifyTabEmailField;
   private javax.swing.JButton ModifyTabLoadButton;
   private javax.swing.JButton ModifyTabSaveButton;
   private javax.swing.JTextField ModifyTabShipAddress1Field;
   private javax.swing.JTextField ModifyTabShipAddress2Field;
   private javax.swing.JTextField ModifyTabShipCityField;
   private javax.swing.JTextField ModifyTabShipFNameField;
   private javax.swing.JTextField ModifyTabShipLNameField;
   private javax.swing.JFormattedTextField ModifyTabShipPhoneField;
   private javax.swing.JComboBox ModifyTabShipStateDropdown;
   private javax.swing.JFormattedTextField ModifyTabShipZIPField;
   private javax.swing.JPanel NewCustomer;
   private javax.swing.JLabel NewPasswordLabel;
   private javax.swing.JTextField NewTabAnswerField;
   private javax.swing.JButton NewTabCancelButton;
   private javax.swing.JPasswordField NewTabConfirmPasswordField;
   private javax.swing.JPasswordField NewTabCreatePasswordField;
   private javax.swing.JTextField NewTabEmailField;
   private javax.swing.JComboBox NewTabQuestionDropdown;
   private javax.swing.JButton NewTabSaveButton;
   private javax.swing.JLabel OlympicPride;
   private javax.swing.JLabel OlympicPride1;
   private javax.swing.JLabel OlympicPride2;
   private javax.swing.JLabel OlympicPride5;
   private javax.swing.JLabel ReqFieldInstruct;
   private javax.swing.JLabel ReqFieldInstruct1;
   private javax.swing.JLabel ResetAnswer;
   private javax.swing.JLabel ResetEMailAddressLabel;
   private javax.swing.JLabel ResetSecurityQuestionLabel;
   private javax.swing.JLabel ShippingInfoLabel;
   private javax.swing.JPanel Test;
   private javax.swing.JButton TestTabLoadCustomersButton;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTabbedPane tabCstLogin;
   // End of variables declaration//GEN-END:variables
}
