
package olympicstore;


public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      tabCstLogin = new javax.swing.JTabbedPane();
      CustomerLogin = new javax.swing.JPanel();
      CstEMailAddressLabel = new javax.swing.JLabel();
      CstPasswordLabel = new javax.swing.JLabel();
      CstEMailAddress = new javax.swing.JTextField();
      btnCstOK = new javax.swing.JButton();
      btnCstCancel = new javax.swing.JButton();
      CstPassword = new javax.swing.JPasswordField();
      OlympicPride = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      NewCustomer = new javax.swing.JPanel();
      ReqFieldInstruct = new javax.swing.JLabel();
      EmailAddress = new javax.swing.JLabel();
      EmailAddressField = new javax.swing.JTextField();
      OlympicPride1 = new javax.swing.JLabel();
      NewPasswordLabel = new javax.swing.JLabel();
      ConfirmNewPasswordLabel = new javax.swing.JLabel();
      CreateNewCustomerPassword = new javax.swing.JPasswordField();
      ConfirmNewCustomerPassword = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      NewCustomerSecurityQuestion = new javax.swing.JComboBox();
      NewCustomerSecurityAnswer = new javax.swing.JTextField();
      btnNewCustomerSave = new javax.swing.JButton();
      btnNewCustomerCancel = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      ForgotPassword = new javax.swing.JPanel();
      ResetEMailAddressLabel = new javax.swing.JLabel();
      ResetSecurityQuestionLabel = new javax.swing.JLabel();
      ResetComboSecurityQuestion = new javax.swing.JComboBox();
      ResetAnswSecurityQuestion = new javax.swing.JTextField();
      ResetEMailAddress = new javax.swing.JTextField();
      btnResetOK = new javax.swing.JButton();
      btnResetCancel = new javax.swing.JButton();
      OlympicPride2 = new javax.swing.JLabel();
      ResetAnswer = new javax.swing.JLabel();
      ReqFieldInstruct1 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      ModifyCustomerInfo = new javax.swing.JPanel();
      btnUpdLoad = new javax.swing.JButton();
      jLabel9 = new javax.swing.JLabel();
      OlympicPride5 = new javax.swing.JLabel();
      EmailAddress1 = new javax.swing.JLabel();
      UpdEmailAddressField = new javax.swing.JTextField();
      ModBillCardNumberLabel = new javax.swing.JLabel();
      ModBillCardExpDateLabel = new javax.swing.JLabel();
      ModBillCardHolderNameLabel = new javax.swing.JLabel();
      ModBillCCNbrField = new javax.swing.JTextField();
      ModBillAcctCardExpDate = new javax.swing.JFormattedTextField();
      ModBillCCHolderField = new javax.swing.JTextField();
      ModShipFirstNameLabel = new javax.swing.JLabel();
      ModShipLastNameLabel = new javax.swing.JLabel();
      ModShipAddress1Label = new javax.swing.JLabel();
      ModShipAddress2Label = new javax.swing.JLabel();
      ModShipCityLabel = new javax.swing.JLabel();
      ModShipStateLabel = new javax.swing.JLabel();
      ModShpFirstNameField = new javax.swing.JTextField();
      ModShipLastNameField = new javax.swing.JTextField();
      ModShipAddress1Field = new javax.swing.JTextField();
      ModShipAddress2Field = new javax.swing.JTextField();
      ModShipCityField = new javax.swing.JTextField();
      ModShipStateDropDown = new javax.swing.JComboBox();
      ModShipZipCode = new javax.swing.JLabel();
      ModShipZipCodeField = new javax.swing.JFormattedTextField();
      ModShipPhoneNumberLabel = new javax.swing.JLabel();
      ModShipPhoneNumberField = new javax.swing.JFormattedTextField();
      ModBillFirstNameLabel = new javax.swing.JLabel();
      ModBillLastNameLabel = new javax.swing.JLabel();
      ModBillAddress1LineLabel = new javax.swing.JLabel();
      ModBillAddress2LineLabel = new javax.swing.JLabel();
      ModBillCityLabel = new javax.swing.JLabel();
      ModBillStateLabel = new javax.swing.JLabel();
      ModBillStateDropDown = new javax.swing.JComboBox();
      ModBillZipCodeLabel = new javax.swing.JLabel();
      ModBillZipCodeField = new javax.swing.JFormattedTextField();
      ModBillFirstNameField = new javax.swing.JTextField();
      ModBillLastNameField = new javax.swing.JTextField();
      ModBillAddress1Field = new javax.swing.JTextField();
      ModBillAddress2Field = new javax.swing.JTextField();
      ModBillCityField = new javax.swing.JTextField();
      ModBillPhoneNumberLabel = new javax.swing.JLabel();
      ModBillPhoneNumberField = new javax.swing.JFormattedTextField();
      ShippingInfoLabel = new javax.swing.JLabel();
      BillingInfoLabel = new javax.swing.JLabel();
      btnModSave = new javax.swing.JButton();
      btnModCancel = new javax.swing.JButton();
      Test = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 892, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 406, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      CstEMailAddressLabel.setText("E-Mail Address");

      CstPasswordLabel.setText("Password");

      btnCstOK.setText("OK");

      btnCstCancel.setText("Cancel");

      CstPassword.setText("jPasswordField1");

      OlympicPride.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride.setText("Olympic Pride");

      jLabel2.setText("Color label");

      javax.swing.GroupLayout CustomerLoginLayout = new javax.swing.GroupLayout(CustomerLogin);
      CustomerLogin.setLayout(CustomerLoginLayout);
      CustomerLoginLayout.setHorizontalGroup(
         CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(CustomerLoginLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(CustomerLoginLayout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addContainerGap())
               .addGroup(CustomerLoginLayout.createSequentialGroup()
                  .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(CustomerLoginLayout.createSequentialGroup()
                        .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(CstEMailAddressLabel)
                           .addComponent(CstPasswordLabel))
                        .addGap(26, 26, 26)
                        .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(CstEMailAddress)
                           .addComponent(CstPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(btnCstOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(btnCstCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addComponent(OlympicPride, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 472, Short.MAX_VALUE))))
      );
      CustomerLoginLayout.setVerticalGroup(
         CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(CustomerLoginLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(OlympicPride, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(CstEMailAddressLabel)
                  .addComponent(CstEMailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(btnCstOK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(CustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(CstPasswordLabel)
               .addComponent(CstPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCstCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(308, Short.MAX_VALUE))
      );

      tabCstLogin.addTab("Customer Login", CustomerLogin);

      NewCustomer.setPreferredSize(new java.awt.Dimension(1328, 432));

      ReqFieldInstruct.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
      ReqFieldInstruct.setForeground(new java.awt.Color(255, 0, 51));
      ReqFieldInstruct.setText("* indicates required field");

      EmailAddress.setText("Email Address *");

      EmailAddressField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            EmailAddressFieldFocusGained(evt);
         }
      });

      OlympicPride1.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride1.setText("Olympic Pride");

      NewPasswordLabel.setText("Create New Password *");

      ConfirmNewPasswordLabel.setText("Confirm New Password *");

      CreateNewCustomerPassword.setText("jPasswordField2");

      ConfirmNewCustomerPassword.setText("jPasswordField2");

      jLabel1.setText("Security Question *");

      jLabel3.setText("Security Answer *");

      NewCustomerSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One:", "What is your mother maiden name", "What is your dog name", "What was your school name" }));

      btnNewCustomerSave.setText("Save");

      btnNewCustomerCancel.setText("Cancel");

      jLabel4.setText("Color Label");

      javax.swing.GroupLayout NewCustomerLayout = new javax.swing.GroupLayout(NewCustomer);
      NewCustomer.setLayout(NewCustomerLayout);
      NewCustomerLayout.setHorizontalGroup(
         NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(NewCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addComponent(OlympicPride1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(ReqFieldInstruct, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(NewCustomerLayout.createSequentialGroup()
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ConfirmNewPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addComponent(NewPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(EmailAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(EmailAddressField)
                           .addComponent(CreateNewCustomerPassword)
                           .addComponent(NewCustomerSecurityQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(NewCustomerSecurityAnswer)
                           .addComponent(ConfirmNewCustomerPassword))))
                  .addGap(161, 161, 161)
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(btnNewCustomerSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnNewCustomerCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addContainerGap(68, Short.MAX_VALUE))))
      );
      NewCustomerLayout.setVerticalGroup(
         NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(NewCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(OlympicPride1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(ReqFieldInstruct))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EmailAddress)
               .addComponent(EmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnNewCustomerSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(NewPasswordLabel)
                     .addComponent(CreateNewCustomerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ConfirmNewCustomerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ConfirmNewPasswordLabel)))
               .addGroup(NewCustomerLayout.createSequentialGroup()
                  .addGap(23, 23, 23)
                  .addComponent(btnNewCustomerCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(NewCustomerSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addGap(6, 6, 6)
            .addGroup(NewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(NewCustomerSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addContainerGap(280, Short.MAX_VALUE))
      );

      tabCstLogin.addTab("New Customers", NewCustomer);

      ResetEMailAddressLabel.setText("E-Mail Address *");

      ResetSecurityQuestionLabel.setText("Security Question *");

      ResetComboSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One:", "What is your mother maiden name", "What is your dog name", "What was your school name" }));
      ResetComboSecurityQuestion.setToolTipText("");

      btnResetOK.setText("OK");

      btnResetCancel.setText("Cancel");

      OlympicPride2.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride2.setText("Olympic Pride");

      ResetAnswer.setText("Answer *");

      ReqFieldInstruct1.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
      ReqFieldInstruct1.setForeground(new java.awt.Color(255, 0, 51));
      ReqFieldInstruct1.setText("* indicates required field");

      jLabel5.setText("Color Label");

      javax.swing.GroupLayout ForgotPasswordLayout = new javax.swing.GroupLayout(ForgotPassword);
      ForgotPassword.setLayout(ForgotPasswordLayout);
      ForgotPasswordLayout.setHorizontalGroup(
         ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ForgotPasswordLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ForgotPasswordLayout.createSequentialGroup()
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(OlympicPride2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ReqFieldInstruct1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ForgotPasswordLayout.createSequentialGroup()
                           .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ResetSecurityQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(ResetEMailAddressLabel)
                              .addComponent(ResetAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addGap(18, 18, 18)
                           .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ResetAnswSecurityQuestion)
                              .addComponent(ResetComboSecurityQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(ResetEMailAddress))
                           .addGap(18, 18, 18)
                           .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(btnResetOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(btnResetCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))))
                  .addGap(0, 479, Short.MAX_VALUE))
               .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      ForgotPasswordLayout.setVerticalGroup(
         ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ForgotPasswordLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(OlympicPride2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ReqFieldInstruct1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
            .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ForgotPasswordLayout.createSequentialGroup()
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ResetEMailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ResetEMailAddressLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ResetComboSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ResetSecurityQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(ResetAnswSecurityQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                     .addComponent(ResetAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addGroup(ForgotPasswordLayout.createSequentialGroup()
                  .addGap(15, 15, 15)
                  .addComponent(btnResetOK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(btnResetCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(230, 230, 230))
      );

      tabCstLogin.addTab("Forgot Password", ForgotPassword);

      btnUpdLoad.setText("Load");

      jLabel9.setText("Color label");

      OlympicPride5.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
      OlympicPride5.setText("Olympic Pride");

      EmailAddress1.setText("Email Address *");

      UpdEmailAddressField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            UpdEmailAddressFieldFocusGained(evt);
         }
      });

      ModBillCardNumberLabel.setText("Card Number");

      ModBillCardExpDateLabel.setText("Card Exp. Date");

      ModBillCardHolderNameLabel.setText("Card Holder Name");

      ModBillCCNbrField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillCCNbrFieldFocusGained(evt);
         }
      });

      ModBillAcctCardExpDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("mm/dd/yyyy"))));

      ModBillCCHolderField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModBillCCHolderFieldActionPerformed(evt);
         }
      });
      ModBillCCHolderField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillCCHolderFieldFocusGained(evt);
         }
      });

      ModShipFirstNameLabel.setText("First Name *");

      ModShipLastNameLabel.setText("Last Name *");

      ModShipAddress1Label.setText("Address 1 *");

      ModShipAddress2Label.setForeground(new java.awt.Color(51, 51, 255));
      ModShipAddress2Label.setText("Address 2");

      ModShipCityLabel.setText("City *");

      ModShipStateLabel.setText("State *");

      ModShpFirstNameField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModShpFirstNameFieldActionPerformed(evt);
         }
      });
      ModShpFirstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShpFirstNameFieldFocusGained(evt);
         }
      });

      ModShipLastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShipLastNameFieldFocusGained(evt);
         }
      });

      ModShipAddress1Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShipAddress1FieldFocusGained(evt);
         }
      });

      ModShipAddress2Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShipAddress2FieldFocusGained(evt);
         }
      });

      ModShipCityField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShipCityFieldFocusGained(evt);
         }
      });

      ModShipStateDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "Washington D.C.", "West Virginia", "Wisconsin", "Wyoming" }));
      ModShipStateDropDown.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModShipStateDropDownActionPerformed(evt);
         }
      });

      ModShipZipCode.setText("Zip Code *");

      try {
         ModShipZipCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      ModShipZipCodeField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModShipZipCodeFieldActionPerformed(evt);
         }
      });
      ModShipZipCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShipZipCodeFieldFocusGained(evt);
         }
      });

      ModShipPhoneNumberLabel.setForeground(new java.awt.Color(51, 51, 255));
      ModShipPhoneNumberLabel.setText("Phone Number");

      try {
         ModShipPhoneNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      ModShipPhoneNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModShipPhoneNumberFieldFocusGained(evt);
         }
      });

      ModBillFirstNameLabel.setText("First Name *");

      ModBillLastNameLabel.setText("Last Name *");

      ModBillAddress1LineLabel.setText("Address 1 *");

      ModBillAddress2LineLabel.setForeground(new java.awt.Color(51, 51, 255));
      ModBillAddress2LineLabel.setText("Address 2");

      ModBillCityLabel.setText("City *");

      ModBillStateLabel.setText("State *");

      ModBillStateDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "Washington D.C.", "West Virginia", "Wisconsin", "Wyoming" }));
      ModBillStateDropDown.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModBillStateDropDownActionPerformed(evt);
         }
      });

      ModBillZipCodeLabel.setText("Zip Code *");

      try {
         ModBillZipCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      ModBillZipCodeField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModBillZipCodeFieldActionPerformed(evt);
         }
      });
      ModBillZipCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillZipCodeFieldFocusGained(evt);
         }
      });

      ModBillFirstNameField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ModBillFirstNameFieldActionPerformed(evt);
         }
      });
      ModBillFirstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillFirstNameFieldFocusGained(evt);
         }
      });

      ModBillLastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillLastNameFieldFocusGained(evt);
         }
      });

      ModBillAddress1Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillAddress1FieldFocusGained(evt);
         }
      });

      ModBillAddress2Field.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillAddress2FieldFocusGained(evt);
         }
      });

      ModBillCityField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillCityFieldFocusGained(evt);
         }
      });

      ModBillPhoneNumberLabel.setForeground(new java.awt.Color(51, 51, 255));
      ModBillPhoneNumberLabel.setText("Phone Number");

      try {
         ModBillPhoneNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      ModBillPhoneNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            ModBillPhoneNumberFieldFocusGained(evt);
         }
      });

      ShippingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      ShippingInfoLabel.setText("Shipping Information");

      BillingInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      BillingInfoLabel.setText("Billing Information");

      btnModSave.setText("Save");

      btnModCancel.setText("Cancel");

      javax.swing.GroupLayout ModifyCustomerInfoLayout = new javax.swing.GroupLayout(ModifyCustomerInfo);
      ModifyCustomerInfo.setLayout(ModifyCustomerInfoLayout);
      ModifyCustomerInfoLayout.setHorizontalGroup(
         ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                              .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(ModShipFirstNameLabel)
                                 .addComponent(ModShipLastNameLabel)
                                 .addComponent(ModShipCityLabel)
                                 .addComponent(ModShipAddress1Label)
                                 .addComponent(ModShipAddress2Label))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addComponent(ModShipAddress2Field)
                                 .addComponent(ModShipAddress1Field)
                                 .addComponent(ModShpFirstNameField)
                                 .addComponent(ModShipLastNameField)
                                 .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                    .addComponent(ModShipStateDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ModShipZipCode)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ModShipZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addComponent(ModShipCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                           .addComponent(ModShipStateLabel)
                           .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                              .addComponent(ModShipPhoneNumberLabel)
                              .addGap(18, 18, 18)
                              .addComponent(ModShipPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                              .addComponent(EmailAddress1)
                              .addGap(18, 18, 18)
                              .addComponent(UpdEmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(btnUpdLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                  .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModifyCustomerInfoLayout.createSequentialGroup()
                  .addComponent(ShippingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(btnModSave)
                        .addGap(28, 28, 28)
                        .addComponent(btnModCancel))
                     .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(ModBillCardHolderNameLabel)
                              .addComponent(ModBillCardExpDateLabel)
                              .addComponent(ModBillCardNumberLabel))
                           .addGap(11, 11, 11)
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ModBillCCNbrField, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                              .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                    .addComponent(ModBillAcctCardExpDate, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addGap(190, 190, 190))
                                 .addComponent(ModBillCCHolderField))))
                        .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(ModBillFirstNameLabel)
                              .addComponent(ModBillLastNameLabel)
                              .addComponent(ModBillCityLabel)
                              .addComponent(ModBillAddress1LineLabel)
                              .addComponent(ModBillAddress2LineLabel)
                              .addComponent(ModBillStateLabel)
                              .addComponent(ModBillPhoneNumberLabel))
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(ModBillAddress2Field)
                              .addComponent(ModBillAddress1Field)
                              .addComponent(ModBillFirstNameField)
                              .addComponent(ModBillLastNameField)
                              .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                 .addComponent(ModBillStateDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addComponent(ModBillZipCodeLabel)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addComponent(ModBillZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(ModBillCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                                 .addGap(22, 22, 22)
                                 .addComponent(ModBillPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(BillingInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(81, 81, 81))
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addComponent(OlympicPride5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))))
      );
      ModifyCustomerInfoLayout.setVerticalGroup(
         ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(OlympicPride5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(24, 24, 24)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(EmailAddress1)
                     .addComponent(UpdEmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnUpdLoad))
                  .addGap(35, 35, 35)
                  .addComponent(ShippingInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                  .addGap(18, 18, 18))
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(BillingInfoLabel)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCardNumberLabel)
                     .addComponent(ModBillCCNbrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCardExpDateLabel)
                     .addComponent(ModBillAcctCardExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCardHolderNameLabel)
                     .addComponent(ModBillCCHolderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(10, 10, 10)))
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModBillFirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModBillLastNameLabel)
                        .addGap(7, 7, 7))
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModBillFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModBillLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                  .addGap(3, 3, 3)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillAddress1LineLabel)
                     .addComponent(ModBillAddress1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillAddress2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillAddress2LineLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillCityLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillStateDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillZipCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModBillStateLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModBillPhoneNumberLabel)
                     .addComponent(ModBillPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModShipFirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModShipLastNameLabel)
                        .addGap(7, 7, 7))
                     .addGroup(ModifyCustomerInfoLayout.createSequentialGroup()
                        .addComponent(ModShpFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModShipLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                  .addGap(3, 3, 3)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModShipAddress1Label)
                     .addComponent(ModShipAddress1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModShipAddress2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModShipAddress2Label))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModShipCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModShipCityLabel))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(ModShipStateLabel)
                     .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ModShipStateDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModShipZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModShipZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ModShipPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ModShipPhoneNumberLabel))))
            .addGap(25, 25, 25)
            .addGroup(ModifyCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnModSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnModCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(66, 66, 66))
      );

      tabCstLogin.addTab("Modify Customer Info", ModifyCustomerInfo);

      jButton1.setText("Load Demo Customers");

      jButton2.setText("Place Demo Orders");

      jButton3.setText("Test_2");

      jButton4.setText("Test_3");

      jButton5.setText("Test_1");

      javax.swing.GroupLayout TestLayout = new javax.swing.GroupLayout(Test);
      Test.setLayout(TestLayout);
      TestLayout.setHorizontalGroup(
         TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(TestLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(765, Short.MAX_VALUE))
      );
      TestLayout.setVerticalGroup(
         TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(TestLayout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(242, Short.MAX_VALUE))
      );

      tabCstLogin.addTab("Test", Test);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabCstLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabCstLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void EmailAddressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailAddressFieldFocusGained
      EmailAddressField.selectAll();
   }//GEN-LAST:event_EmailAddressFieldFocusGained

   private void ModBillPhoneNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillPhoneNumberFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillPhoneNumberFieldFocusGained

   private void ModBillCityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillCityFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillCityFieldFocusGained

   private void ModBillAddress2FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillAddress2FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillAddress2FieldFocusGained

   private void ModBillAddress1FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillAddress1FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillAddress1FieldFocusGained

   private void ModBillLastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillLastNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillLastNameFieldFocusGained

   private void ModBillFirstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillFirstNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillFirstNameFieldFocusGained

   private void ModBillFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBillFirstNameFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillFirstNameFieldActionPerformed

   private void ModBillZipCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillZipCodeFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillZipCodeFieldFocusGained

   private void ModBillZipCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBillZipCodeFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillZipCodeFieldActionPerformed

   private void ModBillStateDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBillStateDropDownActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillStateDropDownActionPerformed

   private void ModShipPhoneNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShipPhoneNumberFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipPhoneNumberFieldFocusGained

   private void ModShipZipCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShipZipCodeFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipZipCodeFieldFocusGained

   private void ModShipZipCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModShipZipCodeFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipZipCodeFieldActionPerformed

   private void ModShipStateDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModShipStateDropDownActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipStateDropDownActionPerformed

   private void ModShipCityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShipCityFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipCityFieldFocusGained

   private void ModShipAddress2FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShipAddress2FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipAddress2FieldFocusGained

   private void ModShipAddress1FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShipAddress1FieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipAddress1FieldFocusGained

   private void ModShipLastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShipLastNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShipLastNameFieldFocusGained

   private void ModShpFirstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModShpFirstNameFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShpFirstNameFieldFocusGained

   private void ModShpFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModShpFirstNameFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModShpFirstNameFieldActionPerformed

   private void ModBillCCHolderFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillCCHolderFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillCCHolderFieldFocusGained

   private void ModBillCCNbrFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ModBillCCNbrFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillCCNbrFieldFocusGained

   private void UpdEmailAddressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UpdEmailAddressFieldFocusGained
      // TODO add your handling code here:
   }//GEN-LAST:event_UpdEmailAddressFieldFocusGained

   private void ModBillCCHolderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBillCCHolderFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_ModBillCCHolderFieldActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel BillingInfoLabel;
   private javax.swing.JPasswordField ConfirmNewCustomerPassword;
   private javax.swing.JLabel ConfirmNewPasswordLabel;
   private javax.swing.JPasswordField CreateNewCustomerPassword;
   private javax.swing.JTextField CstEMailAddress;
   private javax.swing.JLabel CstEMailAddressLabel;
   private javax.swing.JPasswordField CstPassword;
   private javax.swing.JLabel CstPasswordLabel;
   private javax.swing.JPanel CustomerLogin;
   private javax.swing.JLabel EmailAddress;
   private javax.swing.JLabel EmailAddress1;
   private javax.swing.JTextField EmailAddressField;
   private javax.swing.JPanel ForgotPassword;
   private javax.swing.JFormattedTextField ModBillAcctCardExpDate;
   private javax.swing.JTextField ModBillAddress1Field;
   private javax.swing.JLabel ModBillAddress1LineLabel;
   private javax.swing.JTextField ModBillAddress2Field;
   private javax.swing.JLabel ModBillAddress2LineLabel;
   private javax.swing.JTextField ModBillCCHolderField;
   private javax.swing.JTextField ModBillCCNbrField;
   private javax.swing.JLabel ModBillCardExpDateLabel;
   private javax.swing.JLabel ModBillCardHolderNameLabel;
   private javax.swing.JLabel ModBillCardNumberLabel;
   private javax.swing.JTextField ModBillCityField;
   private javax.swing.JLabel ModBillCityLabel;
   private javax.swing.JTextField ModBillFirstNameField;
   private javax.swing.JLabel ModBillFirstNameLabel;
   private javax.swing.JTextField ModBillLastNameField;
   private javax.swing.JLabel ModBillLastNameLabel;
   private javax.swing.JFormattedTextField ModBillPhoneNumberField;
   private javax.swing.JLabel ModBillPhoneNumberLabel;
   private javax.swing.JComboBox ModBillStateDropDown;
   private javax.swing.JLabel ModBillStateLabel;
   private javax.swing.JFormattedTextField ModBillZipCodeField;
   private javax.swing.JLabel ModBillZipCodeLabel;
   private javax.swing.JTextField ModShipAddress1Field;
   private javax.swing.JLabel ModShipAddress1Label;
   private javax.swing.JTextField ModShipAddress2Field;
   private javax.swing.JLabel ModShipAddress2Label;
   private javax.swing.JTextField ModShipCityField;
   private javax.swing.JLabel ModShipCityLabel;
   private javax.swing.JLabel ModShipFirstNameLabel;
   private javax.swing.JTextField ModShipLastNameField;
   private javax.swing.JLabel ModShipLastNameLabel;
   private javax.swing.JFormattedTextField ModShipPhoneNumberField;
   private javax.swing.JLabel ModShipPhoneNumberLabel;
   private javax.swing.JComboBox ModShipStateDropDown;
   private javax.swing.JLabel ModShipStateLabel;
   private javax.swing.JLabel ModShipZipCode;
   private javax.swing.JFormattedTextField ModShipZipCodeField;
   private javax.swing.JTextField ModShpFirstNameField;
   private javax.swing.JPanel ModifyCustomerInfo;
   private javax.swing.JPanel NewCustomer;
   private javax.swing.JTextField NewCustomerSecurityAnswer;
   private javax.swing.JComboBox NewCustomerSecurityQuestion;
   private javax.swing.JLabel NewPasswordLabel;
   private javax.swing.JLabel OlympicPride;
   private javax.swing.JLabel OlympicPride1;
   private javax.swing.JLabel OlympicPride2;
   private javax.swing.JLabel OlympicPride5;
   private javax.swing.JLabel ReqFieldInstruct;
   private javax.swing.JLabel ReqFieldInstruct1;
   private javax.swing.JTextField ResetAnswSecurityQuestion;
   private javax.swing.JLabel ResetAnswer;
   private javax.swing.JComboBox ResetComboSecurityQuestion;
   private javax.swing.JTextField ResetEMailAddress;
   private javax.swing.JLabel ResetEMailAddressLabel;
   private javax.swing.JLabel ResetSecurityQuestionLabel;
   private javax.swing.JLabel ShippingInfoLabel;
   private javax.swing.JPanel Test;
   private javax.swing.JTextField UpdEmailAddressField;
   private javax.swing.JButton btnCstCancel;
   private javax.swing.JButton btnCstOK;
   private javax.swing.JButton btnModCancel;
   private javax.swing.JButton btnModSave;
   private javax.swing.JButton btnNewCustomerCancel;
   private javax.swing.JButton btnNewCustomerSave;
   private javax.swing.JButton btnResetCancel;
   private javax.swing.JButton btnResetOK;
   private javax.swing.JButton btnUpdLoad;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTabbedPane tabCstLogin;
   // End of variables declaration//GEN-END:variables
}
